### ISSUE TITLE
provide Express example as fake server

### ISSUE THREAD

**Issue by carlosrubio** [ptitgraig/bower-nexus-resolver#1]
First thanks a lot for publishing this solution. I would recommend to improve the documentation just by adding the code to mimic the bower registry.

**Comment by ptitgraig** [comment]
Thanks for your feedback.
This is done. See https://github.com/ptitgraig/bower-nexus-resolver/commit/3bb1cc2d8e92dfbbf908bf3c17da7fb1f3003a61
