### ISSUE TITLE
express does not comm with json anymore - plus remove redondant '//'

### ISSUE THREAD

**Issue by pmnc-philippe** [ptitgraig/bower-nexus-resolver#2]
below is a minor fix for express and json in the "server.js" implementing the intermediate registry as proposed. It also includes a second fix to keep prefix as 'nexus://' versus 'nexus:////'. In the example I used the port 8082.

So the .bowerrc should be :

``` javascript
{
  "directory": "bower_components",
  "registry": "http://localhost:8082/nexus-bower/",
  "nexusRegistry": "http://localhost:8081/nexus/content/repositories/npm-bower/",
  "resolvers": [
    "bower-nexus-resolver"
  ]
}
```

The .bowerrc file could be located in your project folder, next to the bower.json file.

``` javascript
var express = require('express'),
    json = require('express-json'),
    http = require('http'),

    config = {
      port: 8082,
      context: 'nexus-bower',
      prefix: 'nexus://'
    },

    app = express(),
    server = http.createServer(app).listen( process.env.PORT || config.port);

app.use( json() );

// wait for a request as: 
// http://<hostname>/<context>/packages/<package-name> 
// respond a simple JSON 
app.get('/' + config.context + '/packages/:name', function(req, res){
    res.json({
        "name": req.params.name,
        "url": config.prefix + req.params.name + '/' +req.params.name
    });
});

console.log("STARTUP:: Express Bower registry simulator server listening on port::", server.address().port, ", environment:: ", app.settings.env);
```

Finally, you may want to create on your nexus a npm-bower local repository dedicated to bower packages and npm publish downloaded bower packages. **Does any one know a tool that jsut does that** ? 

  **troubleshooting**
- to see info about bower use -j and -V options: `javascript  bower -j -V install angular`
- to see info about your express server launch it: `javascript set DEBUG=express:* & grunt server` 
- clear bower cache

**Comment by ptitgraig** [comment]
A new release 0.2.3 is available with your changes.
