### ISSUE TITLE
Error when passing config when downloading

### ISSUE THREAD

**Issue by momiji** [ptitgraig/bower-nexus-resolver#3]
Hello, sorry for this very fast comment, but my colleague had a problem while trying to pass strictSsl = false config parameter to the resolver.

His goal is to pass strictSsl=false for the moment, and in a near future, to pass a specific ca.

While tracking why this was not working, I discovered an error in the code.

In index.js, in the download call, the 3rd parameter is this.config, which is always null. It should be bower.config or maybe leave it to this.config but in that case one should add config: bower.config in the returned object.

Hope this is clear, I asked him to send a pull request to correct this bug.

regards

**Comment by ptitgraig** [comment]
Thanks for reporting this issue. I'll have a look and let you know.

**Comment by ptitgraig** [comment]
a new release 0.2.3 is available with your bugfix
